#

apiVersion: v1
kind: Service
metadata:
  name: sitemgr
  labels:
    app.kubernetes.io/name: csm
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app.kubernetes.io/name: csm
