#

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: site-agent
  labels:
    app.kubernetes.io/name: elektra-site-agent
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: elektra-site-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: site-agent
subjects:
  - kind: ServiceAccount
    name: site-agent
    namespace: "elektra-site-agent"
---
