#

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: site-agent
  labels:
    app.kubernetes.io/name: elektra-site-agent
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: elektra-site-agent
rules:
  - apiGroups: ["", "cert-manager.io"]
    resources: ["certificaterequests", "secrets"]
    verbs: ["*"]
---
