/*
Code is generated
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// SiteListerExpansion allows custom methods to be added to
// SiteLister.
type SiteListerExpansion interface{}

// SiteNamespaceListerExpansion allows custom methods to be added to
// SiteNamespaceLister.
type SiteNamespaceListerExpansion interface{}
