#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-policy:elektra-site-agent
rules:
  - apiGroups:
      - policy.cert-manager.io
    resourceNames:
      - site-agent-approver-policy
    resources:
      - certificaterequestpolicies
    verbs:
      - use
---
