#

apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: credsmgr-policy-approver
spec:
  allowed:
    commonName:
      required: false
      value: "*"
    dnsNames:
      required: false
      values:
        - "*"
    ipAddresses:
      values:
        - 127.0.0.1
    isCA: false
    usages:
      - server auth
      - client auth
    subject:
      organizations:
        required: false
        values:
          - "*"
  selector:
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: vault-issuer
    namespace:
      matchNames:
        - temporal
        - cloud-db
        - cloud-workflow
        - cloud-api
