#

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki/sign/cloud-cert
    server: http://credsmgr:8200
    auth:
      tokenSecretRef:
        name: vault-token
        key: token
