#

---
# Source: cert-manager/templates/sa-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credsmgr
  namespace: "cert-manager"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
