// SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common_carbide.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineId) Reset() {
	*x = MachineId{}
	mi := &file_common_carbide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineId) ProtoMessage() {}

func (x *MachineId) ProtoReflect() protoreflect.Message {
	mi := &file_common_carbide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineId.ProtoReflect.Descriptor instead.
func (*MachineId) Descriptor() ([]byte, []int) {
	return file_common_carbide_proto_rawDescGZIP(), []int{0}
}

func (x *MachineId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MachineIdList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineIds    []*MachineId           `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineIdList) Reset() {
	*x = MachineIdList{}
	mi := &file_common_carbide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineIdList) ProtoMessage() {}

func (x *MachineIdList) ProtoReflect() protoreflect.Message {
	mi := &file_common_carbide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineIdList.ProtoReflect.Descriptor instead.
func (*MachineIdList) Descriptor() ([]byte, []int) {
	return file_common_carbide_proto_rawDescGZIP(), []int{1}
}

func (x *MachineIdList) GetMachineIds() []*MachineId {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_common_carbide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_common_carbide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_common_carbide_proto_rawDescGZIP(), []int{2}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Uint32List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []uint32               `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uint32List) Reset() {
	*x = Uint32List{}
	mi := &file_common_carbide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uint32List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint32List) ProtoMessage() {}

func (x *Uint32List) ProtoReflect() protoreflect.Message {
	mi := &file_common_carbide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint32List.ProtoReflect.Descriptor instead.
func (*Uint32List) Descriptor() ([]byte, []int) {
	return file_common_carbide_proto_rawDescGZIP(), []int{3}
}

func (x *Uint32List) GetItems() []uint32 {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_common_carbide_proto protoreflect.FileDescriptor

const file_common_carbide_proto_rawDesc = "" +
	"\n" +
	"\x14common_carbide.proto\x12\x06common\"\x1b\n" +
	"\tMachineId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\rMachineIdList\x122\n" +
	"\vmachine_ids\x18\x01 \x03(\v2\x11.common.MachineIdR\n" +
	"machineIds\"\x1c\n" +
	"\x04UUID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"Uint32List\x12\x14\n" +
	"\x05items\x18\x01 \x03(\rR\x05itemsBBZ@github.com/NVIDIA/carbide-rest-api/carbide-rest-api-schema/protob\x06proto3"

var (
	file_common_carbide_proto_rawDescOnce sync.Once
	file_common_carbide_proto_rawDescData []byte
)

func file_common_carbide_proto_rawDescGZIP() []byte {
	file_common_carbide_proto_rawDescOnce.Do(func() {
		file_common_carbide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_carbide_proto_rawDesc), len(file_common_carbide_proto_rawDesc)))
	})
	return file_common_carbide_proto_rawDescData
}

var file_common_carbide_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_carbide_proto_goTypes = []any{
	(*MachineId)(nil),     // 0: common.MachineId
	(*MachineIdList)(nil), // 1: common.MachineIdList
	(*UUID)(nil),          // 2: common.UUID
	(*Uint32List)(nil),    // 3: common.Uint32List
}
var file_common_carbide_proto_depIdxs = []int32{
	0, // 0: common.MachineIdList.machine_ids:type_name -> common.MachineId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_carbide_proto_init() }
func file_common_carbide_proto_init() {
	if File_common_carbide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_carbide_proto_rawDesc), len(file_common_carbide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_carbide_proto_goTypes,
		DependencyIndexes: file_common_carbide_proto_depIdxs,
		MessageInfos:      file_common_carbide_proto_msgTypes,
	}.Build()
	File_common_carbide_proto = out.File
	file_common_carbide_proto_goTypes = nil
	file_common_carbide_proto_depIdxs = nil
}
