# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
#

FROM redocly/redoc:v2.4.0

ENV PAGE_TITLE="Nvidia Forge API 1.0"
ENV PAGE_FAVICON=https://www.nvidia.com/favicon.ico
ENV SPEC_URL=openapi.yaml

COPY ./schema/reference/Forge-Cloud-v1.yaml /usr/share/nginx/html/openapi.yaml
